<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>NVDARemoteAudioHelper</AssemblyName>
    <RootNamespace>NVDARemoteAudioHelper</RootNamespace>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Concentus" Version="*" />
    <PackageReference Include="Concentus.Native" Version="*" />
    <PackageReference Include="Concentus.Native.NetCore" Version="*" />
    <PackageReference Include="NAudio" Version="*" />
  </ItemGroup>

</Project>
